import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, './components.css');
const componentsDir = resolve(__dirname, '../components');

// Light-DOM component styles live in <name>/<name>.styles.js, keyed by tag.
// Shadow components keep theirs on the class, because they adopt them at
// runtime; these are only ever read here.
const entries = [];
for (const dir of readdirSync(componentsDir, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const stylesPath = resolve(componentsDir, dir.name, `${dir.name}.styles.js`);
  if (!existsSync(stylesPath)) continue;
  const { default: styles } = await import(pathToFileURL(stylesPath).href);
  entries.push(...Object.entries(styles));
}

const styles = entries
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([tag, css]) => `/* ${tag} */\n${css.trim()}`)
  .join('\n\n');

const css = `/* Generated by src/css/build.js — do not edit */\n\n${styles}\n`;

writeFileSync(outPath, css, 'utf8');
console.log(`styles → ${outPath}`);
