import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as components from '../components/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, './components.css');

const styles = Object.values(components)
  .filter((component) => (
    typeof component === 'function' &&
    typeof component.tag === 'string' &&
    component.styles &&
    component.shadow !== true
  ))
  .sort((left, right) => left.tag.localeCompare(right.tag))
  .map((component) => `/* ${component.tag} */\n${component.styles.trim()}`)
  .join('\n\n');

const css = `/* Generated by src/css/build.js — do not edit */\n\n${styles}\n`;

writeFileSync(outPath, css, 'utf8');
console.log(`styles → ${outPath}`);
